import PDFDocument from "pdfkit";
import { formatCurrency } from "../utils/money.js";

/**
 * Streams a professional invoice PDF into a Buffer.
 * Only ever called on APPROVED invoices (enforced in controller).
 */
export const generateInvoicePdf = (invoice) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50 });
    const chunks = [];

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Header
    doc.fontSize(20).text("INVOICE", { align: "right" });
    doc.fontSize(10).fillColor("#555").text(invoice.invoiceNumber, { align: "right" });
    doc
      .text(`Date: ${new Date(invoice.createdAt).toLocaleDateString("en-IN")}`, {
        align: "right",
      })
      .fillColor("#000");

    doc.moveDown(2);

    // From / Bill To
    doc.fontSize(12).text("Bill To:", { underline: true });
    doc.fontSize(11).text(invoice.customer.name || "N/A");
    if (invoice.customer.email) doc.text(invoice.customer.email);
    if (invoice.customer.phone) doc.text(invoice.customer.phone);

    doc.moveDown(1.5);

    // Table header
    const tableTop = doc.y;
    doc.fontSize(10).fillColor("#fff");
    doc.rect(50, tableTop, 500, 20).fill("#2c3e50");
    doc
      .fillColor("#fff")
      .text("Service", 55, tableTop + 5, { width: 200 })
      .text("Qty", 260, tableTop + 5, { width: 50, align: "right" })
      .text("Unit Price", 320, tableTop + 5, { width: 100, align: "right" })
      .text("Total", 430, tableTop + 5, { width: 110, align: "right" });

    let y = tableTop + 25;
    doc.fillColor("#000").fontSize(10);

    invoice.items.forEach((item, idx) => {
      const bg = idx % 2 === 0 ? "#f7f7f7" : "#ffffff";
      doc.rect(50, y - 3, 500, 20).fill(bg);
      doc
        .fillColor("#000")
        .text(item.matchedService || item.requestedText, 55, y, { width: 200 })
        .text(String(item.quantity), 260, y, { width: 50, align: "right" })
        .text(formatCurrency(item.unitPricePaise || 0), 320, y, { width: 100, align: "right" })
        .text(formatCurrency(item.lineTotalPaise || 0), 430, y, { width: 110, align: "right" });
      y += 20;
    });

    y += 10;
    doc.moveTo(320, y).lineTo(550, y).stroke();
    y += 8;

    doc.text("Subtotal:", 320, y, { width: 100, align: "right" });
    doc.text(formatCurrency(invoice.subtotalPaise), 430, y, { width: 110, align: "right" });
    y += 18;

    doc.text(`Tax (${invoice.taxRatePercent}%):`, 320, y, { width: 100, align: "right" });
    doc.text(formatCurrency(invoice.taxAmountPaise), 430, y, { width: 110, align: "right" });
    y += 18;

    doc.fontSize(12).font("Helvetica-Bold");
    doc.text("Total:", 320, y, { width: 100, align: "right" });
    doc.text(formatCurrency(invoice.totalPaise), 430, y, { width: 110, align: "right" });
    doc.font("Helvetica");

    if (invoice.notes) {
      doc.moveDown(3);
      doc.fontSize(10).fillColor("#555").text(`Notes: ${invoice.notes}`);
    }

    doc.moveDown(2);
    doc
      .fontSize(8)
      .fillColor("#999")
      .text("Generated by Kodnexus Smart Invoice — AI-assisted, human-approved.", {
        align: "center",
      });

    doc.end();
  });
};
